"""모드, 자금 배분, 필터, 리스크, 로그 설정을 모아둔 중앙 설정 파일."""

import os


def _env_str(name: str, default: str) -> str:
    raw = os.getenv(name)
    if raw is None or str(raw).strip() == "":
        return str(default)
    return str(raw).strip()


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or str(raw).strip() == "":
        try:
            return int(default)
        except Exception:
            return 0
    try:
        return int(str(raw).strip())
    except Exception:
        try:
            return int(default)
        except Exception:
            return 0


# ===============================
# BOT mode
# ===============================
MODE = "MAIN"  # MAIN / SAFE / TEST
BOT_MODE = MODE  # backward compatibility
REAL_ORDER = MODE != "TEST"
REQUIRE_ORDER_CONFIRM = False

ENABLE_MAIN_STRATEGY = True
ENABLE_SCALP_STRATEGY = False

# Legacy SCALP(11~30) and BTC-only SCALP switch
SCALP_LEGACY_ENABLED = False
SCALP_BTC_ENABLED = True

# ===============================
# Universe / loop
# ===============================
TOP_N = 10
UNIVERSE_SCAN_N = 30
CORE_TOP_N = 10
CORE_MIN_ACTIVE = 3
CORE_STRICT_PREFILTER = False
SURGE_RANK_START = 11
SURGE_RANK_END = 30
SURGE_KEEP_MINUTES = 10
SURGE_STOPLOSS_REENTRY_BLOCK_MIN = 45

SPIKE_CANDIDATE_MAX = 3
SPIKE_RANK_SURGE_MIN = 5
SPIKE_VOL_LOOKBACK_MIN = 5
SPIKE_VOL_MULT = 1.2
SPIKE_RSI_CROSS_LEVEL = 50
SPIKE_MA_FAST = 5
SPIKE_MA_SLOW = 20

REFRESH_MIN = 5
MARKET_INFO_REFRESH_MIN = 1
POLL_SEC = 1
MIN_ORDER_KRW = 5_000
SCAN_LOG_TOPN = 10
SCAN_PROGRESS_LOG = False

NO_DUPLICATE_TICKER_ACROSS_STRATEGIES = True
ALLOW_ADD_BUY = False
EXCLUDE_CAUTION = True
BLOCK_MARKET_WARNING = True
BLOCK_ENTRY_WHEN_MARKET_INFO_UNAVAILABLE = True

DEBUG_STOP_PCT = False
DEBUG_TRADE_FLOW = True
DEBUG_ENTRY_REJECT = False

# ===============================
# Costs
# ===============================
# Buy 0.05% + Sell 0.05% + slippage buffer
COST_ROUNDTRIP_PCT = 0.0015

# ===============================
# Technical indicator compatibility
# ===============================
# RSI mode:
# - RMA: TradingView/Wilder style (recommended for parity)
# - SMA: simple rolling mean style (legacy)
TA_RSI_MODE = "RMA"
# Bollinger std ddof:
# - 0: population std (TradingView-like default)
# - 1: sample std (pandas default)
TA_BB_STD_DDOF = 0

# ===============================
# Market regime
# ===============================
USE_MARKET_REGIME = False

REGIME_INVEST_FRAC = {
    "HALT": 0.0,
    "LOW": 0.7,
    "MID": 0.7,
    "FULL": 0.7,
}
REGIME_HOLDINGS_MULT = {
    "HALT": 1.0,
    "LOW": 1.0,
    "MID": 1.0,
    "FULL": 1.0,
}

BTC_REGIME_FAST_MA = 5
BTC_REGIME_SLOW_MA = 20
BTC_REGIME_RSI_PERIOD = 14

# ===============================
# Strategy auto mode
# ===============================
AUTO_STRATEGY_MODE = True
AUTO_STRATEGY_RECHECK_SEC = 60
AUTO_STRATEGY_TOPN = 10
AUTO_STRATEGY_RSI_INTERVAL = "day"

# ===============================
# Account sizing
# ===============================
TEST_EQUITY_CAP = 200_000
TEST_PER_TRADE_KRW = 30_000
MINUTE_TEST_PER_TRADE_KRW = 30_000
TEST_MAX_HOLDINGS = 2

# Keep 2 holdings until this equity.
HOLDINGS_FIXED_UNTIL_EQUITY = 1_500_000

# Tier-based expansion above HOLDINGS_FIXED_UNTIL_EQUITY
ACCOUNT_TIERS = [
    {"min_equity": 1_500_001, "max_holdings": 3},
    {"min_equity": 2_000_001, "max_holdings": 4},
    {"min_equity": 3_000_001, "max_holdings": 5},
]

HOLDING_SCALE = {
    2: 1.00,
    3: 0.90,
    4: 0.80,
    5: 0.75,
}

# ===============================
# Risk / exits
# ===============================
STOP_LOSS_PCT = 0.010
STOP_LOSS_MODE = "ATR"  # FIXED / ATR
STOP_LOSS_ATR_PERIOD = 14
STOP_LOSS_ATR_MULT_TABLE = {"LOW": 0.66, "MID": 0.78, "FULL": 0.90, "HALT": 0.60}
STOP_LOSS_MIN_PCT = 0.010
STOP_LOSS_MAX_PCT = 0.016

TP_TABLE = {
    "LOW": {"TP1_PCT": 0.010, "TP2_PCT": 0.020, "TRAIL_BACK_PCT": 0.004},
    "MID": {"TP1_PCT": 0.010, "TP2_PCT": 0.020, "TRAIL_BACK_PCT": 0.005},
    "FULL": {"TP1_PCT": 0.010, "TP2_PCT": 0.020, "TRAIL_BACK_PCT": 0.007},
    "HALT": {"TP1_PCT": 0.0, "TP2_PCT": 0.0, "TRAIL_BACK_PCT": 0.0},
}
TP1_SELL_RATIO = 0.50
TP2_SELL_RATIO = 0.50
TRAIL_BACK_PCT = 0.0070

# Trailing arm guard (percent-based fields, not ratio):
# - TRAIL_ARM_PCT: minimum unrealized profit (%) to enable trailing
# - TRAIL_DRAWDOWN_PCT: optional trailing drawdown (%) override; None = use regime TRAIL_BACK_PCT
TRAIL_ARM_SEC = 120
TRAIL_ARM_PCT = 0.5
TRAIL_DRAWDOWN_PCT = None

# MAIN one-shot take profit (ratio). 0 disables.
MAIN_TP_ONE_PCT = 0.0

# MAIN staged take-profit profile by AUTO_STRATEGY_MODE.
# The ratios are normalized at runtime and persisted per-position on entry.
MAIN_TP_RATIOS = {
    "CONSERVATIVE": {"TP1": 0.50, "TP2": 0.30, "RUNNER": 0.20},
    "AGGRESSIVE": {"TP1": 0.50, "TP2": 0.30, "RUNNER": 0.20},
}

# After TP1 hit on MAIN, move stop to break-even (entry +/- buffer).
MAIN_BE_AFTER_TP1_ENABLED = True
MAIN_BE_AFTER_TP1_BUFFER_PCT = 0.0

# Small account safety profile (applied on new MAIN entries only).
SMALL_EQUITY_MAIN_TP_PROFILE_ENABLED = True
SMALL_EQUITY_MAIN_TP_MAX_EQUITY = 200_000
SMALL_EQUITY_MAIN_TP_RATIOS = {"TP1": 0.60, "TP2": 0.00, "RUNNER": 0.40}

# MAIN runner (remaining size after TP2 partial) controls
MAIN_RUNNER_TRAIL_GIVEBACK_PCT = 0.007
MAIN_RUNNER_MAX_HOLD_MIN = 120
MAIN_RUNNER_TIMEOUT_CLOSE_IF_PNL_GE = 0.0

TP_SL_BY_HOLDINGS = {
    2: {
        "tp1": 0.008,
        "tp2": 0.014,
        "tp1_ratio": 0.50,
        "tp2_ratio": 0.30,
        "trail_back": 0.0070,
        "stop_fixed": 0.016,
        "daily_tp1_stop": 3,
        "consec_loss_stop": 4,
    },
    3: {
        "tp1": 0.007,
        "tp2": 0.012,
        "tp1_ratio": 0.55,
        "tp2_ratio": 0.30,
        "trail_back": 0.0075,
        "stop_fixed": 0.014,
        "daily_tp1_stop": 4,
        "consec_loss_stop": 5,
    },
    4: {
        "tp1": 0.006,
        "tp2": 0.010,
        "tp1_ratio": 0.60,
        "tp2_ratio": 0.25,
        "trail_back": 0.0080,
        "stop_fixed": 0.012,
        "daily_tp1_stop": 5,
        "consec_loss_stop": 6,
    },
    5: {
        "tp1": 0.0055,
        "tp2": 0.009,
        "tp1_ratio": 0.65,
        "tp2_ratio": 0.20,
        "trail_back": 0.0085,
        "stop_fixed": 0.011,
        "daily_tp1_stop": 6,
        "consec_loss_stop": 7,
    },
}

DAILY_TP1_STOP_COUNT = TP_SL_BY_HOLDINGS[2]["daily_tp1_stop"]
CONSEC_LOSS_STOP_COUNT = TP_SL_BY_HOLDINGS[2]["consec_loss_stop"]
DAILY_TP1_EXIT_LIMIT = 3
CONSEC_LOSS_EXIT_LIMIT = 4
MAIN_CONSEC_LOSS_LIMIT = 4
SCALP_CONSEC_LOSS_LIMIT = 4

COOLDOWN_PROFIT_MIN = 10
COOLDOWN_LOSS_MIN = 30

# Global risk-cut (account-level circuit breaker)
# negative percent values: -5 means -5%
DAILY_MAX_LOSS_PCT = -5.0
GLOBAL_MDD_LIMIT_PCT = -15.0
RISK_CUT_FORCE_CLOSE = False
# Require consecutive breaches before risk-cut fires (spike guard).
RISK_CUT_CONFIRM_TICKS = 3
# If equity drops sharply while no position is held, treat it as transient API noise
# until this many consecutive ticks confirm the drop.
RISK_EQUITY_DROP_GUARD_PCT = 0.20
RISK_EQUITY_DROP_GUARD_TICKS = 30
# When no position is held, keep using last-good equity on suspicious drops
# to prevent false account-level risk halts from transient KRW balance glitches.
RISK_EQUITY_DROP_GUARD_STRICT_NO_HOLDINGS = True

# ===============================
# MAIN strategy
# ===============================
K_DEFAULT = 0.5
AUTO_K = True
K_LOOKBACK_DAYS = 30
K_CANDIDATES = [
    0.10,
    0.15,
    0.20,
    0.25,
    0.30,
    0.35,
    0.40,
    0.45,
    0.50,
    0.55,
    0.60,
    0.65,
    0.70,
    0.75,
    0.80,
    0.85,
    0.90,
    0.95,
]

USE_INTRADAY_FILTER = False
INTRADAY_TREND_INTERVAL = "minute240"
INTRADAY_FAST_MA = 20
INTRADAY_SLOW_MA = 60

ENTRY_MINUTE_INTERVAL = "minute5"
ENTRY_FAST_MA = 5
ENTRY_SLOW_MA = 20
ENTRY_RSI_PERIOD = 14
ENTRY_RSI_MAX = 70
ENTRY_ENABLE_TREND_RSI_RELAX = True
ENTRY_RSI_MAX_STRONG = 74
ENTRY_MA_SLOPE_BARS = 1
ENTRY_NEAR_HIGH_BLOCK_PCT = 0.002
ENTRY_PULLBACK_MIN_PCT = 0.003
ENTRY_PULLBACK_MAX_PCT = 0.010
ENTRY_PULLBACK_LOOKBACK = 20
ENTRY_PULLBACK_WINDOW = 8
ENTRY_REQUIRE_REBOUND = True
ENTRY_REQUIRE_VOL_HOLD = True
ENTRY_MINUTE_REJECT_SUMMARY_MIN = 10
ENTRY_MINUTE_REJECT_SUMMARY_TOPN = 6
ENTRY_RSI_CROSS_LEVEL = 45
ENTRY_RSI_DELTA_MIN = 1.5
ENTRY_MA_FAST = 5
ENTRY_MA_SLOW = 20
ENTRY_USE_VOLUME_FILTER = True
ENTRY_VOL_MA_PERIOD = 20
ENTRY_VOL_MULT = 1.2
ENTRY_USE_BREAKOUT = True
ENTRY_BREAKOUT_LOOKBACK = 20
ENTRY_REQUIRE_RSI_UPTURN = False

# Extra guard for non-core surge-like MAIN entries.
# This does not alter core majors (BTC/ETH/XRP by default).
SURGE_EXTRA_GUARD_ENABLED = True
SURGE_EXTRA_GUARD_INTERVAL = "minute1"
SURGE_EXTRA_GUARD_CACHE_SEC = 5
SURGE_EXTRA_GUARD_EXEMPT_TICKERS = {"KRW-BTC", "KRW-ETH", "KRW-XRP"}
SURGE_EXTRA_GUARD_1M_MAX_PCT = 3.0
SURGE_EXTRA_GUARD_5M_MAX_PCT = 10.0
SURGE_EXTRA_GUARD_BODY_MAX_PCT = 2.5

# MAIN additional 1m confirmation (applied only in CONSERVATIVE mode)
USE_1M_CONFIRM_FOR_MAIN = True
MAIN_CONFIRM_1M_INTERVAL = "minute1"
MAIN_CONFIRM_1M_RSI_PERIOD = 14
MAIN_CONFIRM_1M_RSI_DELTA_MIN = 0.3
MAIN_CONFIRM_1M_REQUIRE_REBOUND = True
MAIN_CONFIRM_1M_CACHE_SEC = 5

MAIN_FILTER_REJECT_SUMMARY_MIN = 10
MAIN_FILTER_REJECT_SUMMARY_TOPN = 6

# MAIN entry score gate (minute timing replacement)
ENTRY_SCORE_ENABLED = True
ENTRY_SCORE_REPLACE_MINUTE_OK = True
MAIN_MIN_ENTRY_SCORE = 3
ENTRY_SCORE_INTERVAL = "minute1"
ENTRY_SCORE_LOOKBACK = 40
ENTRY_SCORE_CACHE_SEC = 5
ENTRY_SCORE_VOL_MULT = 1.80
ENTRY_SCORE_RSI_MAX = 60.0
ENTRY_SCORE_LOG_BLOCKED = True
ENTRY_SCORE_LOG_PASS = False

# MAIN universe extension with surge candidates/ranked pool
MAIN_INCLUDE_SURGE = True
MAIN_SURGE_SOURCE = "RANKED"

# V5 strategy (5m breakout + pullback, R-multiple exits)
ENABLE_V5_STRATEGY = False
V5_REGIME_FILTER_ON = False
V5_REGIME_BLOCKED = {"HALT"}
# V5 BTC trend gate (optional): block all V5 entries when BTC trend is weak.
V5_BTC_FILTER_ON = False
V5_BTC_FILTER_TICKER = "KRW-BTC"
V5_BTC_FILTER_TF = "minute240"
V5_BTC_FILTER_MODE = "EMA200_UP"  # EMA200_UP / MA20_GT_MA60 / MA_FAST_GT_SLOW / MA20_OVER_MA60_RATIO
V5_BTC_FILTER_EMA_LEN = 200
V5_BTC_FILTER_MA_FAST = 20
V5_BTC_FILTER_MA_SLOW = 60
V5_BTC_FILTER_MA_RATIO_MIN = 0.995
V5_SIGNAL_INTERVAL = "minute5"
V5_SIGNAL_LOOKBACK = 120
V5_ENTRY_PARALLEL_WORKERS = 1
V5_BREAKOUT_LOOKBACK = 30
# Legacy alias kept for CLI/script convenience.
V5_VOLUME_MULT = 2.1
V5_BREAKOUT_VOL_MULT = 2.1
V5_BREAKOUT_CONFIRM_PCT = 0.0015
V5_BREAKOUT_QUALITY_FILTER = False
V5_BREAKOUT_CLOSE_TOP_PCT = 0.25
V5_BREAKOUT_UPPER_WICK_MAX_BODY = 0.50
V5_BREAKOUT_MIN_BODY_PCT = 0.0010
V5_BREAKOUT_MIN_RANGE_PCT = 0.0015
V5_REL_STRENGTH_FILTER_ON = True
V5_RS_BTC_TICKER = "KRW-BTC"
V5_RS_LOOKBACK_BARS = 12
V5_RS_MIN_EXCESS_PCT = 0.20
V5_RS_EXEMPT_TICKERS = {"KRW-BTC"}
V5_UNIVERSE_MOM_FILTER_ON = False
V5_UNIVERSE_MOM_LOOKBACK_BARS = 12
V5_UNIVERSE_MOM_TOP_N = 3
V5_BTC_VOL_CAP_ON = True
V5_BTC_VOL_TICKER = "KRW-BTC"
V5_BTC_VOL_TF = "minute60"
V5_BTC_VOL_ATR_PERIOD = 14
V5_BTC_VOL_LOOKBACK = 80
V5_BTC_VOL_CAP_PCT = 1.0
V5_PULLBACK_MAX_BARS = 2
V5_EMA_PERIOD = 20
V5_TREND_FILTER = "CLOSE_GT_EMA50"  # OFF / CLOSE_GT_EMA50 / EMA20_GT_EMA50
V5_VOL_MA_PERIOD = 20
# Optional retest confirmation after breakout (quality gate).
V5_REQUIRE_RETEST_CONFIRM = False
V5_RETEST_TOUCH_TOL_PCT = 0.0015
V5_RETEST_BREAK_TOL_PCT = 0.0030
V5_RETEST_RECLAIM_MIN_PCT = 0.0
V5_SL_MIN_PCT = 0.010
V5_SL_MAX_PCT = 0.020
V5_TP1_R = 1.3
V5_TP2_R = 2.8
V5_RUNNER_ARM_R = 4.0
V5_RUNNER_TRAIL_BACK_R = 1.0
V5_RUNNER_MAX_HOLD_MIN = 240
V5_RUNNER_TIMEOUT_CLOSE_IF_PNL_GE = 0.0
V5_TP_RATIOS = {"TP1": 0.45, "TP2": 0.30, "RUNNER": 0.25}

# REGIME_SWITCH strategy (backtest-only): BTC 4h regime + V5(A)/mean-reversion(B)/off(C)
RSW_BTC_TICKER = "KRW-BTC"
RSW_BTC_TF = "minute240"
RSW_CONFIRM_BARS = 2

RSW_EMA_FAST = 20
RSW_EMA_SLOW = 60
RSW_ADX_PERIOD = 14
RSW_BULL_ADX_MIN = 18.0
RSW_SIDE_MA_DIST_MAX = 0.004
RSW_SIDE_ADX_MAX = 18.0
RSW_ATR_MED_BARS = 180
RSW_BB_LEN = 20
RSW_BB_K = 2.0
RSW_BB_MED_BARS = 180

RSW_MAX_HOLDINGS_A = 2
RSW_MAX_HOLDINGS_B = 1
RSW_A_PER_TRADE_SCALE = 1.0
RSW_B_ONLY_WHEN_A_IDLE = False
RSW_B_REQUIRE_SIDEWAYS = True
RSW_B_USE_TOTAL_HOLDINGS_CAP = False

RSW_B_EXEC_TF = "minute5"
RSW_B_LOOKBACK = 240
RSW_B_RSI_PERIOD = 14
RSW_B_RSI_MAX = 32.0
RSW_B_VWAP_STD_Z = 1.2
RSW_B_NO_BREAKOUT_BARS = 3
RSW_B_REQUIRE_REBOUND_CLOSE = False
RSW_B_REQUIRE_STRONG_REBOUND = False
RSW_B_REBOUND_EMA_LEN = 8
RSW_B_VOLUME_FILTER_ON = False
RSW_B_VOL_MA_BARS = 20
RSW_B_VOL_MULT_MIN = 1.1
RSW_B_RISK_PCT = 0.01
RSW_B_SL_PCT = 0.008
RSW_B_TP_PCT = 0.010
RSW_B_TIMEOUT_MIN = 90
RSW_B_FORCE_EXIT_ON_REGIME_CHANGE = True

# MF_RANK strategy (backtest-only, multi-factor ranking without runner)
MF_SIGNAL_TF = "minute5"
MF_SIGNAL_LOOKBACK = 160
MF_ENTRY_INTERVAL_MIN = 5
MF_UNIVERSE_TOPN = 15
MF_UNIVERSE_RECALC_HOURS = 4
MF_EXCLUDE_TICKERS = []

MF_MOM_LOOKBACK = 12
MF_VOL_MA = 20
MF_ATR_PERIOD = 14
MF_ATR_PCTL_LOOKBACK = 96
MF_VWAP_WINDOW = 96
MF_RANK_WORKERS = 8

MF_W_MOMENTUM = 0.30
MF_W_REL_STRENGTH = 0.25
MF_W_VOLUME = 0.20
MF_W_VOLATILITY = 0.10
MF_W_REVERSION = 0.15
MF_MIN_SCORE = 0.60

MF_BTC_TICKER = "KRW-BTC"
MF_BTC_TF = "minute240"
MF_BTC_EMA_FAST = 20
MF_BTC_EMA_SLOW = 60
MF_BTC_NEG_RISK_MULT = 0.5

MF_RISK_PCT = 0.020
MF_TP_PCT = 0.015
MF_SL_PCT = 0.010
MF_TIMEOUT_MIN = 180

# TREND_H1 strategy (backtest-only, 4h trend following + 1h breakout)
ENABLE_TREND_H1_STRATEGY = False
TREND_H1_BTC_TICKER = "KRW-BTC"
TREND_H1_BTC_TF = "minute240"
TREND_H1_BTC_EMA_LEN = 200
TREND_H1_BTC_MA_FAST = 20
TREND_H1_BTC_MA_SLOW = 60
TREND_H1_BTC_FILTER_MODE = "HARD"  # HARD / OFF / SOFT_RISK
TREND_H1_BTC_SOFT_RISK_PCT = 0.005
TREND_H1_SIGNAL_TF = "minute240"
TREND_H1_ENTRY_TF = "minute60"
TREND_H1_EMA_LEN = 200
TREND_H1_RSI_PERIOD = 14
TREND_H1_RSI_MIN = 58.0
TREND_H1_BREAKOUT_LOOKBACK = 15
TREND_H1_STOP_PCT = 0.05
TREND_H1_TRAIL_PCT = 0.09
TREND_H1_EXIT_EMA_TF = "minute240"
TREND_H1_EXIT_EMA_LEN = 20
TREND_H1_RISK_PCT = 0.01
TREND_H1_ENTRY_PARALLEL_WORKERS = 8

# SELECTIVE_TREND strategy (backtest-only, aggressive selective trend following)
ENABLE_SELECTIVE_TREND_STRATEGY = False
SELECTIVE_TREND_BTC_TICKER = "KRW-BTC"
SELECTIVE_TREND_BTC_4H_TF = "minute240"
SELECTIVE_TREND_BTC_WEEK_TF = "week"
SELECTIVE_TREND_BTC_4H_EMA_LEN = 200
SELECTIVE_TREND_BTC_4H_MA_FAST = 20
SELECTIVE_TREND_BTC_4H_MA_SLOW = 60
SELECTIVE_TREND_BTC_WEEK_EMA_LEN = 20
SELECTIVE_TREND_USE_BTC_WEEK_FILTER = True
SELECTIVE_TREND_SIGNAL_TF = "minute240"
SELECTIVE_TREND_ENTRY_TF = "minute60"
SELECTIVE_TREND_EMA_LEN = 200
SELECTIVE_TREND_RSI_PERIOD = 14
SELECTIVE_TREND_RSI_MIN = 60.0
SELECTIVE_TREND_BREAKOUT_LOOKBACK = 20
SELECTIVE_TREND_VOL_MA_PERIOD = 20
SELECTIVE_TREND_VOL_MULT = 1.5
SELECTIVE_TREND_STOP_PCT = 0.06
SELECTIVE_TREND_TRAIL_PCT = 0.15
SELECTIVE_TREND_RISK_PCT = 0.015
SELECTIVE_TREND_ENTRY_PARALLEL_WORKERS = 8

# HL_PULLBACK_TREND strategy (backtest-only, pullback trend continuation)
ENABLE_HL_PULLBACK_TREND_STRATEGY = False
HLPT_BTC_TICKER = "KRW-BTC"
HLPT_BTC_TF = "minute240"
HLPT_BTC_EMA_LEN = 200
HLPT_BTC_MA_FAST = 20
HLPT_BTC_MA_SLOW = 60
HLPT_SIGNAL_TF = "minute240"
HLPT_ENTRY_TF = "minute60"
HLPT_EMA_LEN = 200
HLPT_LOOKBACK = 30
HLPT_PULLBACK_BARS_MIN = 3
HLPT_PULLBACK_BARS_MAX = 6
# Legacy alias (kept for backward compatibility)
HLPT_MIN_PULLBACK_BARS = 3
HLPT_PULLBACK_MIN_PCT = 0.03
HLPT_PULLBACK_MAX_PCT = 0.08
HLPT_RSI_PERIOD = 14
HLPT_RISK_PCT = 0.015
HLPT_FIXED_STOP_PCT = 0.045
HLPT_TP1_R = 2.0
HLPT_TRAIL_PCT = 0.10
HLPT_EXIT_EMA_TF = "minute240"
HLPT_EXIT_EMA_LEN = 20
HLPT_ENTRY_PARALLEL_WORKERS = 8

# ORB_SESSION_V1 strategy (backtest-only, 09:06~09:30 KST opening range breakout)
ENABLE_ORB_SESSION_V1_STRATEGY = False
ORB_BTC_TICKER = "KRW-BTC"
ORB_BTC_TF = "minute240"
ORB_BTC_EMA_LEN = 200
ORB_BTC_MA_FAST = 20
ORB_BTC_MA_SLOW = 60
ORB_BTC_RSI_PERIOD = 14
ORB_BTC_RSI_MIN = 50.0
ORB_ENTRY_START_HOUR = 9
ORB_ENTRY_START_MIN = 6
ORB_ENTRY_END_HOUR = 9
ORB_ENTRY_END_MIN = 30
ORB_ENTRY_MODE = "BREAKOUT"  # BREAKOUT | RETEST
ORB_BREAKOUT_BUFFER_PCT = 0.0
ORB_RETEST_TOL_PCT = 0.0015
ORB_RETEST_MIN_AFTER_BREAK_BARS = 1
ORB_RETEST_MAX_DELAY_BARS = 8
ORB_RETEST_REQUIRE_CLOSE_ABOVE_OPENING = True
ORB_RETEST_VOL_REEXPAND_MULT = 1.0
ORB_SIGNAL_TF = "minute5"
ORB_RSI_PERIOD = 14
ORB_RSI_MIN = 55.0
ORB_VOL_LOOKBACK = 5
ORB_VOL_MULT = 1.2
ORB_STOP_CAP_PCT = 0.018
ORB_TP1_PCT = 0.02
ORB_TP2_PCT = 0.035
ORB_TP1_RATIO = 0.50
ORB_TP2_RATIO = 0.30
ORB_RUNNER_RATIO = 0.20
ORB_RUNNER_TRAIL_PCT = 0.015
ORB_TIMEOUT_MIN = 60
ORB_TIMEOUT_MIN_PROGRESS_PCT = 0.5
ORB_RISK_PCT = 0.01
ORB_BASE_R_PCT = 0.01
ORB_DAILY_MAX_R = 2.5
ORB_MAX_DAILY_TRADES = 1
ORB_ENTRY_PARALLEL_WORKERS = 8

# SR_ONLY strategy (pure support/resistance box)
ENABLE_SR_ONLY_STRATEGY = False
SR_ZONE_INTERVAL = "minute15"
SR_EXEC_INTERVAL = "minute5"
SR_SIGNAL_LOOKBACK_15M = 360
SR_SIGNAL_LOOKBACK_5M = 240
SR_LOOKBACK = 20
SR_DELTA_VOL_LEN = 2
SR_BOX_ATR_MULT = 1.0
SR_USE_EMA_TREND_FILTER = True
SR_EMA_LEN = 200
SR_USE_VOL_Z_FILTER = True
SR_VOL_Z_LEN = 50
SR_VOL_Z_MIN = 0.3
SR_RETEST_ATR5_MULT = 0.10
SR_RETEST_FIXED_PCT = 0.0015
SR_SL_OFFSET_PCT = 0.003
SR_TP_MODE = "R_FIXED"  # R_FIXED / RESIST
SR_TP_R = 2.0
SR_TIMEOUT_MIN = 0
SR_COOLDOWN_BARS = 40
SR_REQUIRE_FLIP_BREAK_BEFORE_RESIGNAL = True

# SR_ONLY_TV_COMBO strategy (YouTube S/R + trading rules)
ENABLE_SR_ONLY_TV_COMBO = False
# Backward-compatible alias.
ENABLE_SR_TV_COMBO_STRATEGY = False
SR_TV_ZONE_INTERVAL = "minute15"
SR_TV_EXEC_INTERVAL = "minute5"
SR_TV_SIGNAL_LOOKBACK_15M = 360
SR_TV_SIGNAL_LOOKBACK_5M = 240
SR_TV_LOOKBACK = 20
SR_TV_DELTA_VOL_LEN = 2
SR_TV_BOX_ATR_MULT = 1.0
SR_TV_USE_EMA_TREND_FILTER = True
SR_TV_EMA_LEN = 200
SR_TV_USE_VOL_Z_FILTER = True
SR_TV_VOL_Z_LEN = 50
SR_TV_VOL_Z_MIN = 0.3
SR_TV_RETEST_TOL_PCT = 0.0015
SR_TV_COOLDOWN_BARS = 40
SR_TV_MAX_TOUCH_COUNT = 3
SR_TV_REQUIRE_FLIP_BREAK_BEFORE_RESIGNAL = True
SR_TV_SL_BUFFER_PCT = 0.003
SR_TV_VERSION = "V1"  # V1 | V2_RECLAIM | V2_EMA200 | V2_VOLCONF
SR_TV_RECLAIM_ON = True
SR_TV_EMA200_ON = True
SR_TV_VOLCONF_ON = True
SR_TV_VOLCONF_MA_N = 20
SR_TV_VOLCONF_MULT = 1.0

# Conservative soft bypass for DAY_MA_FAIL bottleneck (MAIN only).
# Note: only DAY_MA_FAIL is bypass-eligible.
DAY_MA_SOFT_BYPASS_ENABLED = True
DAY_MA_BYPASS_REQUIRE_ENTRY_SCORE = 3
DAY_MA_BYPASS_REQUIRE_H4_TREND = True
DAY_MA_BYPASS_REQUIRE_VOL_OK = True
DAY_MA_BYPASS_COOLDOWN_MIN = 60
DAY_MA_BYPASS_LOG = True

# 09:00 KST opening volatility guard (new entries only)
ENABLE_0900_ENTRY_GUARD = True
ENTRY_GUARD_START_HOUR = 9
ENTRY_GUARD_START_MIN = 0
ENTRY_GUARD_END_HOUR = 9
ENTRY_GUARD_END_MIN = 15
ENTRY_GUARD_NOTIFY_TELEGRAM = False

# ===============================
# SCALP strategy
# ===============================
USE_MINUTE_TEST_STRATEGY = True
MINUTE_TEST_INTERVAL = "minute1"

MINUTE_TEST_RSI_LOW = 45
MINUTE_TEST_RSI_HIGH = 60
MINUTE_TEST_RSI_CROSS = True
MINUTE_TEST_RSI_DELTA_MIN = 1.5
MINUTE_TEST_USE_VOLUME_FILTER = True
MINUTE_TEST_VOL_MA_PERIOD = 20
MINUTE_TEST_VOL_MULT = 1.2
MINUTE_TEST_REQUIRE_GREEN_CANDLE = True
MINUTE_TEST_USE_MA_FILTER = True
MINUTE_TEST_MA_FAST = 5
MINUTE_TEST_MA_SLOW = 20
MINUTE_TEST_REQUIRE_PRICE_ABOVE_SLOW = True
MINUTE_TEST_USE_BREAKOUT = True
MINUTE_TEST_BREAKOUT_LOOKBACK = 20

# SCALP stabilization extensions
SCALP_CONFIRM_BARS = 2
SCALP_BREAKOUT_LOOKBACK = 20
SCALP_RSI_MIN = 52.0
SCALP_RSI_DELTA_MIN = 0.6
SCALP_MA_FAST = 5
SCALP_MA_SLOW = 20
SCALP_VOL_MA_PERIOD = 20
SCALP_VOL_MULT = 1.4
SCALP_CONSERVATIVE_RSI_MIN = 52.0
SCALP_CONSERVATIVE_VOL_MULT = 1.5
SCALP_RSI_MAX = 72.0
SCALP_BREAKOUT_MAX_GAP_PCT = 0.008
SCALP_MAX_CANDLE_BODY_PCT = 0.012
SCALP_DAWN_START_HOUR = 0
SCALP_DAWN_END_HOUR = 7
SCALP_DAWN_CONSERVATIVE = True
SCALP_DAWN_BLOCK = True
SCALP_LOSSSEQ_CONSERVATIVE_TRIGGER = 1
SCALP_PAUSE_ON_LOSSSEQ = True
SCALP_PAUSE_LOSSSEQ_TRIGGER = 2
SCALP_PAUSE_MINUTES = 60

# ===============================
# SCALP_BTC strategy (KRW-BTC only)
# ===============================
SCALP_BTC_TICKER = "KRW-BTC"
SCALP_BTC_TF = "minute15"

SCALP_BTC_MAX_SHARE = 0.20
SCALP_BTC_PER_TRADE_SHARE = 0.10
SCALP_BTC_MAX_POSITIONS = 1
SCALP_BTC_BLOCK_WHEN_MAIN_HOLDING = False

SCALP_BTC_RSI_LEN = 14
SCALP_BTC_RSI_OS = 28
SCALP_BTC_VOL_LOOKBACK = 20
SCALP_BTC_VOL_SPIKE_MULT = 1.5
SCALP_BTC_VOL_SPIKE_WINDOW = 3
SCALP_BTC_EMA_FAST = 9

# SCALP_BTC: regime filter (4h trend)
SCALP_BTC_REGIME_FILTER_ON = True
SCALP_BTC_REGIME_TF = "minute240"
SCALP_BTC_REGIME_MA_FAST = 20
SCALP_BTC_REGIME_MA_SLOW = 60
SCALP_BTC_REGIME_MODE = "BULL_ONLY"
SCALP_BTC_REGIME_CACHE_SEC = 300

SCALP_BTC_TP_PCT = 0.012
SCALP_BTC_SL_PCT = 0.009
SCALP_BTC_MAX_HOLD_MIN = 90
SCALP_BTC_TIMEOUT_PROFIT_MIN = 0.0

SCALP_BTC_TRAIL_ON = True
SCALP_BTC_TRAIL_FROM = 0.010
SCALP_BTC_TRAIL_GIVEBACK = 0.006

SCALP_BTC_COOLDOWN_PROFIT_MIN = 10
SCALP_BTC_COOLDOWN_LOSS_MIN = 30
SCALP_BTC_MAX_LOSS_STREAK = 2
SCALP_BTC_PAUSE_MIN_AFTER_STREAK = 60

SCALP_BTC_SWITCH_FAIL_LIMIT = 3
SCALP_BTC_SWITCH_FAIL_PAUSE_MIN = 60
SCALP_BTC_LOCK_TIMEOUT_SEC = 5
SCALP_BTC_MIN_ORDER_BUFFER = 1.02

# ===============================
# State / logging
# ===============================
STATE_FILE = "bot_state.json"
STATE_SAVE_INTERVAL_SEC = 30
INSTANCE_LOCK_PATH = "/home/ubuntu/upbit-bot/.upbit_bot.instance.lock"

TRADE_LOG_PATH = "trade_log.csv"
STATUS_PRINT_SEC = 60

# ===============================
# Reporting
# ===============================
AUTO_REPORT = True
AUTO_REPORT_MIN_INTERVAL_SEC = 30
AUTO_REPORT_QUIET = True
AUTO_REPORT_SAVE_XLSX = False
DAILY_REPORT_SEND_MONTH_IMAGE = False
TELEGRAM_SPOOL_FLUSH_SEC = 30
TELEGRAM_SPOOL_FLUSH_LIMIT = 50
INITIAL_CAPITAL = 1_000_000

# Telegram notification policy
TELEGRAM_PARTIAL_NOTIFY = False
TELEGRAM_0900_REPORT_ENABLED = False
TELEGRAM_2100_REPORT_ENABLED = False

# Daily report / heartbeat schedule gate (KST)
REPORT_SEND_KST_HOUR = 21
REPORT_SEND_KST_MIN = 0
HEARTBEAT_SEND_KST_HOUR = 9
HEARTBEAT_SEND_KST_MIN = 0
REPORT_SCHEDULE_WINDOW_MIN = 30
REPORT_SCHEDULE_STATE_FILE = "report_schedule_state.json"

# Settlement sanity guards
SETTLEMENT_MIN_SELL_RATIO = 0.55
CLOSE_NOTIFY_DEDUPE_SEC = 10

# ===============================
# Position management
# ===============================
POSITION_TARGET_MULT = 2.0
POSITION_MAX_BUY_COUNT = 2
DUST_CLOSE_AS_CLOSED = True

# ===============================
# Filter caches
# ===============================
DAY_FILTER_CACHE_SEC = 60
INTRADAY_FILTER_CACHE_SEC = 30
MINUTE_ENTRY_CACHE_SEC = 10

# ===============================
# Order retry / order log
# ===============================
ORDER_RETRY_MAX = 3
ORDER_RETRY_SLEEP_SEC = 0.35
ORDER_LOG_PATH = "order_log.csv"

