[Service]
RuntimeDirectory=upbit-bot
RuntimeDirectoryMode=0755

ExecStartPost=/bin/bash -lc 'FLAG_FILE="/run/upbit-bot/%n.failed_flag"; if [ -f "$FLAG_FILE" ]; then rm -f "$FLAG_FILE"; fi'
ExecStopPost=/bin/bash -lc 'date +%%s > /run/upbit-bot/%n.last_stop || true'
